"""initial schema

Revision ID: 3780c100b430
Revises: ef359456e494
Create Date: 2026-01-06 15:08:29.251848

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3780c100b430"
down_revision: Union[str, Sequence[str], None] = "ef359456e494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "molecules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("formula", sa.String(length=100), nullable=False),
        sa.Column("molecular_weight", sa.Float(), nullable=False),
        sa.Column("smiles", sa.Text(), nullable=False),
        sa.Column("inchi", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_molecular_weight", "molecules", ["molecular_weight"], unique=False
    )
    op.create_index(
        "idx_molecule_name_formula", "molecules", ["name", "formula"], unique=False
    )
    op.create_index(op.f("ix_molecules_id"), "molecules", ["id"], unique=False)
    op.create_index(op.f("ix_molecules_name"), "molecules", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_molecules_name"), table_name="molecules")
    op.drop_index(op.f("ix_molecules_id"), table_name="molecules")
    op.drop_index("idx_molecule_name_formula", table_name="molecules")
    op.drop_index("idx_molecular_weight", table_name="molecules")
    op.drop_table("molecules")
    # ### end Alembic commands ###
